apiVersion: apps/v1
kind: Deployment
metadata:
  name: rides-production
  labels:
    app: rides
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rides
      provides: production
  template:
    metadata:
      labels:
        app: rides
        provides: production
    spec:
      containers:
        - name: rides
          image: gcr.io/mta-music-318515/rides:production
          ports:
            - containerPort: 80
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: password
            - name: DB_NAME
              value: rides

---
apiVersion: v1
kind: Service
metadata:
  name: rides-production
  labels:
    app: rides
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: rides
    provides: production
